name: Bike Share Data Collection
on:
  schedule:
    - cron: '0 */4 * *'
  workflow_dispatch:
jobs:
  collect-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libmysqlclient-dev \
            libproj-dev \
            libgdal-dev \
            libudunits2-dev \
            libgeos-dev \
            libssl-dev \
            libcurl4-openssl-dev \
            libxml2-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-renv: true

      - name: Install R packages
        run: |
          Rscript -e "install.packages('renv', repos = 'https://packagemanager.posit.co/cran/latest')"
          Rscript -e "renv::restore(repos = 'https://packagemanager.posit.co/cran/latest')"

      - name: Set up environment variables
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "DB_HOST=$DB_HOST" >> .Renviron
          echo "DB_USER=$DB_USER" >> .Renviron
          echo "DB_PASSWORD=$DB_PASSWORD" >> .Renviron

      - name: Run Master Workflow Script
        run: |
          Rscript update_app.R

      - name: Commit updated data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add update_app.R
          git diff --staged --quiet || (git commit -m "Update data using the update_app file" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
